### ISSUE TITLE
Multiple value CSS properties

### ISSUE THREAD

**Issue by davidbwaters** [juliangarnier/anime#109]
Hi, I was attempting to animate between CSS properties with multiple values.  For example, `backgroundPosition: ['0 0%', '0 100%'],`
Also, it would be nice to do this with CSS values that accept multiple declarations, like multiple backgrounds.
`backgroundPosition: ['0 0, 0 0%', '0 0, 0 100%'],`
I was having trouble animating values that contained more than one number, but this could be useful for colors also:
`backgroundImage: ['linear-gradient( 90deg, #eee, #fff)', 'linear-gradient( 90deg, #ccc, #fff)'];`

Not sure if I'm doing something wrong.
I tried using a `+` to add string values to the number I wanted to animate, and that didn't work either.

Also, I couldn't get it to synchronize animating a clip path from an initial value (or one set with CSS) the first time an animation is played.

**Comment by juliangarnier** [comment]
Hello,

For the background position, try using units everywhere, like this : `['0% 0%', '0% 100%']`.
Demo here : http://codepen.io/juliangarnier/pen/GrVWJE/

Concerning the gradient, that one is tricky since the values are mixed between percents and colors.
Colors value have to be converted to rgb and rounded because rgb doesn't accept decimals.

I don't think Anime will support css gradient animation, not with the current code base anyway.
I should add this exception to the documentation.

But if you really wants to use Anime for this effect, you can use a JS object and change the styles using update() like this http://codepen.io/juliangarnier/pen/xgvPQo?editors=0010

**Comment by davidbwaters** [comment]
Hi, thanks.  Maybe add an example of using Anime like this (possibly with a few more object properties) to the docs.  This makes Anime very powerful for trickier values with different types of numbers nested in parenthesis like gradient, clip-path, filter, etc.  I managed to get close to what I was trying to accomplish by updating the example with a degree property (this is the only type of gradient animation you can't 'fake' with CSS transparency):  http://codepen.io/davidbwaters/pen/RpbPyq?editors=0010

I could probably smooth it out with different easings, but it I'm attempting to make it less abrupt/jerky on reversing the rotation.  Is there any way to add a custom duration to a specific property?

**Comment by juliangarnier** [comment]
> Is there any way to add a custom duration to a specific property?

Yes like this: 

```
var animation = anime({
  targets: gradients,
  start: {
    value: '#8453E3',
    duration: 4000,
    easing: 'easeOutExpo'
  },
  end: {
    value: '#FBF38C',
    duration: 2000,
    easing: 'easeOutQuad'
  },
...
```

**Comment by kalpriksh** [comment]
Is this still working?....The codepen example now shows nothing or has this been updated?

**Comment by BrisaBoards** [comment]
@kalpriksh If you click the settings icon next to the JS box, you can click in the CDN search box, type animejs, select the first one, and when you close it, it'll reload and start working :)
