### ISSUE TITLE
what's the state of anime?

### ISSUE THREAD

**Issue by PierBover** [juliangarnier/anime#13]
Is it production ready?

Do you have an eta for 1.0?

**Comment by joseluisq** [comment]
`anime` is really cool!
but I'm asking me the same question..

**Comment by juliangarnier** [comment]
Thanks @joseluisq,

I'm currently working with it on small projects, and I'm happy with the current state of the library, that's why I decided to share it with others.
But knowing that I've been the only one to use this, it's hard to guarantee a 100% bug free library.

I'll add features and bug fix when I can, but for me this is 1.0.

**Comment by PierBover** [comment]
Great

@juliangarnier maybe you could add a 1.0 release tag?

**Comment by joseluisq** [comment]
@juliangarnier Sure, one release tag would be great :octocat:

**Comment by juliangarnier** [comment]
Done! https://github.com/juliangarnier/anime/releases/tag/v1.0

**Comment by towry** [comment]
It has some issues on safari and mobile browsers. It works well on Chrome browser on desktop.
