### ISSUE TITLE
Target starts at incorrect top value

### ISSUE THREAD

**Issue by Flascher** [juliangarnier/anime#135]
I've been working on an animation for my portfolio page (love the library by the way!) and I ran into an issue where the top value seems to be multiplied incorrectly. I have CSS that starts the target at top: 20rem, with the intention of animating to top: 15rem (which it does), but as soon as its animation begins it jumps to top: 242.403rem for some reason.

I've provided a codepen that demonstrates the issue [here](http://codepen.io/Flascher/pen/gmozYR).

Ignore the poor positioning, slightly messy code, and the default font. It's still a work in progress :)

**Comment by juliangarnier** [comment]
It's because `getComputedStyle(el).top` will return the value converted in px, not rem.
In that case 20rem = 320px.
So anime will try to animate from 320em to 15em.
When working with non-default units like `rem` of `vh`, It's safer to specify the initial value using an array, like this: `top: ['20rem', '15rem']`.
