### ISSUE TITLE
Timeline finished issues

### ISSUE THREAD

**Issue by luglio7** [juliangarnier/anime#159]
Hi folks, great lib.

I don't think this should work since this feature is undocumented but i would like the 'finished' promise of timelines to be triggered after the last tween is completed, now the promise is resolved after the first tween.

**Comment by snc** [comment]
I had this issue, too. If your timeline only contains one animation, it works as expected. If the timeline contains multiple animations, the `finished` promise gets fired instantly, not after the first animation ends.
A workaround for this issue is setting `delay` and `offset` accordingly, see https://codepen.io/anon/pen/oWzxmb.

**Comment by luglio7** [comment]
I also solved this by wrapping the timeline in a Promise and set the resolve call to the complete callback of the last tween. I would like to see this feature fixed / implemented because that would be very handy.

**Comment by juliangarnier** [comment]
Looks like a bug.
Thanks for reporting it.

**Comment by darkylmnx** [comment]
i had the same bug too with the current version

**Comment by siassaj** [comment]
+1

**Comment by luglio7** [comment]
exactly the same :)

**Comment by LuisAlejandro** [comment]
I'm experiencing this bug on version 3.0, I have a timeline with several animations and the promise fires inmediately.

**Comment by LuisAlejandro** [comment]
@juliangarnier It works! Thank you, great work!
