### ISSUE TITLE
Trigger on hover + multiple targets

### ISSUE THREAD

**Issue by wassim** [juliangarnier/anime#186]
I'm trying to trigger anime when hovering on a target and apply this to more than one selector, for exemple every li in a ul list or every button etc.

See pen: https://codepen.io/anon/pen/qjOKEY

Thanks!

**Comment by MichaelRise** [comment]
Hey,

You must create loop

```
var buttonEl = document.getElementsByTagName('button');
for (var i = 0; i < buttonEl.length; i++) {
  var btn = buttonEl[i];
  animateButton(btn);
}

function animateButton(btn) {
  [...]
}
```

**Comment by alexchantastic** [comment]
Alternatively, if you're just scaling the button like that, why not just use CSS?

**Comment by wassim** [comment]
@MichaelRise A classic loop is only working for the last element. Can't figure out why.
@alexchantastic I'm looking to use more animations than scaling.

**Comment by alexchantastic** [comment]
The loop isn't working because you are using `document.querySelector` which will return the first element that it finds a match for in the DOM. You need to use `document.querySelectorAll` or `document.getElementsByTagName` as @MichaelRise suggested.

Here is a working example: https://codepen.io/alexchantastic/pen/XgXbgz
