### ISSUE TITLE
Opera issue

### ISSUE THREAD

**Issue by mczaja** [juliangarnier/anime#201]
Check your script on Opera browser (mac). After browser update doesn't work properly.

**Comment by MichaelRise** [comment]
I have this same problem on Opera 46 (win 8.1).

**Comment by TomS-** [comment]
I have the same problem, weirdly Opera is built on Chromium. I use it because it's Chrome with some nice extra features Always on Top video, Build in Ad Blocker and the sidebar. 

Since only 1.1% of the population use it, I think anime.js is still fine to use. I'm thinking this is more of an Opera issue than a AnimeJS issue.

**Comment by AndersSchmidtHansen** [comment]
FYI: Had the problem with Opera 46, but seems fixed in Opera 47 (Linux).

**Comment by juliangarnier** [comment]
Check on Opera 47 (Mac) and everything is working perfectly.
