### ISSUE TITLE
Timeline with play and reverse function.

### ISSUE THREAD

**Issue by nosugarsociety** [juliangarnier/anime#233]
There is a timeline which has 3 different elements ( .square, .circle, .triangle) and try to move these to 250px right side when click "test" and move back to its original position when click "test" again.
So, I made this absoluteOffset timeline set autoplay false and made .test element can get click event. But, When we click .test element at first time, all of these elements moves to 250px right side at once and comes back to its position. This is not what I expected. After we click .test once, It is working fine as I expected. What's the problem on here? To get this effect, should I make another timeline to control movement to move elements to reverse? 

This is my code example. 
https://codepen.io/nosugarsociety/pen/eEbZdE

**Comment by Delanyo32** [comment]
@nosugarsociety I have seen this problem before. The fix is quite simple really, however the sample code on the website does not work as we it to expect (i think it has something to do with the timeline). 

Looks as if when both functions are ran, it cancels the play method and runs the reverse method first

In order to achieve what your looking for, you will have to check the "completed" variable and run the reverse function when the animation has completed.
see example below

`    menuBtn.on('click',function () {
       //menuAnimeT1 is the animejs  object with the timeline 
         menuAnimeT1.play();
      //checks whether the animation has been completed and runs the reverse
        if(menuAnimeT1.completed){
            menuAnimeT1.reverse();
        }`

**Comment by nosugarsociety** [comment]
Hi! @Delanyo32 I appreciated your help on this. I have not really thought about 'completed' callback option. It works great as I expected.
