### ISSUE TITLE
How to use rotate3d animation?

### ISSUE THREAD

**Issue by JasonBoy** [juliangarnier/anime#272]
I tried: 
```
anime({
    transform: [
          'rotate3d(1,0,1,90deg)',
          'rotate3d(1,0,1,0deg)',
        ],
})
//and
anime({
    rotate3d: [
          '1,0,1,90deg',
          '1,0,1,0deg',
        ],
})
```
But looks like it did not work, any other way to use `rotate3d`?

**Comment by mdkq** [comment]
Not sure if you can use rotate3d exactly (as in, defining the vector that you're rotating around), but you might be able to get similar functionality out of this:

```javascript
var elt = document.getElementById("item");
elt.style.transformOrigin = "50% 50% -150px";

anime({
  targets: item,
  rotateX: 10,
  rotateY: 20,
  rotateZ: 30
})
```

Minorly more performant I think since you're not querying for DOM elements twice:

```javascript
anime({
  targets: item,
  rotateX: 10,
  rotateY: 20,
  rotateZ: 30,
  before: function(e) {
    e.animatables[0].target.style.transformOrigin = "50% 50% -150px";
  }
})
```

I think if you wanted to do some pre-rotations before the animation you'd need to do something like this:

```javascript
anime({
  targets: item,
  rotateX: 10,
  rotateY: [20, 20], // to avoid being overwritten
  rotateZ: [30, 30],
  before: function(e) {
    e.animatables[0].target.style.transformOrigin = "50% 50% -150px";
    e.animatables[0].target.style.transform = "rotateY(20) rotateZ(30)";
  }
})
```
Not completely sure on that last one; if someone knows something less hacky I'd love to hear it.

Does that solve your problem?

**Comment by JasonBoy** [comment]
@mdkq I've fallback to use rotateX,,Y,X separately, at least close to the effect I want, but maybe it's even greater to support `rotate3d` natively by the library 😆

**Comment by mdkq** [comment]
Could be! Though, from what I've noticed when @juliangarnier doesn't include functionality it's usually because it would add a lot of weight to the library.

**Comment by juliangarnier** [comment]
No plans for adding this for now.
