### ISSUE TITLE
animating an SVG `transform` attribute

### ISSUE THREAD

**Issue by robjtede** [juliangarnier/anime#340]
Since CSS transforms on SVG items doesn't work in IE (and doesn't seem to work for <mask> elements in Firefox, using the `transform` attribute is preferred.

Attempting to animate it with a value such as `translate(0 -100)` results in `<rect> attribute transform: Unexpected end of attribute. Expected ')', "translate(0 ".`.

**Comment by juliangarnier** [comment]
Hey good catch!

It's because the browser will get the initial value from the computed styles, and will return `'translate(0)'` and the second value (y) will be undefined.

It's fixed in v3, you can use it now but there is no proper changelog yet.

Or define the initial value yourself, like this `transform: ['translate(0 0), 'translate(0 -100)]`

**Comment by robjtede** [comment]
@juliangarnier awesome to see this has been caught already.

might have to try the 3.0 branch out, thanks :)

**Comment by juliangarnier** [comment]
Should be fixed in V3.
