### ISSUE TITLE
Bug discovered

### ISSUE THREAD

**Issue by babakness** [juliangarnier/anime#362]
Hello,

See this animation:

https://codepen.io/babakness/pen/zjOrmd

Notice how the yellow box fades out then fades back in. Now, see this codepen

https://codepen.io/babakness/pen/rvBxPw

Here the yellow fades out but then jump back to full opacity without a fade.

The only difference between the two is 1/1000 of a second offset on the second entry to the timeline. I've noticed a similar issue using keyframes (no timeline).

**Comment by juliangarnier** [comment]
Hello,

I see fade-in / fade-out animations in both examples, but maybe you changed your CodePen example since your post.

But if you set the delay of your first timeline animation to `3000` and then the offset of the second animation to `3000`, both animations will be played at the same time.
Setting the offset to `3001` will create an animation from the first value (with `delay: 3000`) to the second one (`offset: 3001`) with a duration of `1ms`.

That can explain why you don't see the fade.
