### ISSUE TITLE
Animations not working properly on elements with css transition applied

### ISSUE THREAD

**Issue by eliasghorwall** [juliangarnier/anime#376]
Setting for example `transition: all .35s ease` on an element and then trying to animate it with anime.js results in very weirdly behaving animations.

Example: https://codepen.io/elias-g/pen/PeMjVw

**Comment by alexchantastic** [comment]
I think this is a given that you're mixing two methods of animating an element (CSS based animation/transition vs JS). What's your particular use case here?

**Comment by eliasghorwall** [comment]
Main use case is on for example buttons that should have some kind of hover transition. Setting that makes it impossible to additionally animate it with anime.js. How could I get around this?

**Comment by alexchantastic** [comment]
You could move to use CSS animations instead.

If you would like to continue to leverage anime, you can procedurally add the `transition` CSS declaration to the element using a callback or promise after the animation finishes. Or do the same, but instead of adding the CSS property to the element, just add a CSS class that contains the `transition` to the element.

**Comment by alexchantastic** [comment]
Depending on what transitions and animations you want to achieve, the easy way would be to only have `transition` target the individual properties that you want to transition instead of `all`.

However, if you must use `all`, then removing the `transition` from the element and then adding it back after the animation has completed would be a good starting point. Something like this: https://codepen.io/alexchantastic/pen/zavXzq/

The issue with the example though is if you are transitioning and animating on the same property. In this case, you would need to re-declare the `:hover` transition with the end result of your animation.

**Comment by eliasghorwall** [comment]
Awesome, thank you!
