### ISSUE TITLE
CSS transform properties ignored except last (more than one anime instances on the same target)

### ISSUE THREAD

**Issue by potouridisio** [juliangarnier/anime#384]
Hello there,

I came across with the following problem.

Transitions on `CSS properties` execute at the same time on one element as expected.

```
anime({
  targets: ".example",
  color: "#39cccc",
  duration: 3000
});

anime({
  targets: ".example",
  fontSize: "30px",
  duration: 3000
});
```

anime yet executes only last `CSS Transform property` on one element.

```
anime({
  targets: ".example",
  translateX: 200,
  duration: 3000
});

anime({
  targets: ".example",
  translateY: 200,
  duration: 3000
});
```

You can see an example [here](https://codesandbox.io/s/lr530moro7?module=%2Fsrc%2Findex.js)

**Comment by acemir** [comment]
Hi @potouridisio!
I think this is the expected behavior, since `transform` is interpreted by the browsers as a single `CSS property`.
If you need to animate more than one `CSS Transform property` in the same element, you must pass all of them to the same anime instance, as in the [example](http://animejs.com/documentation/#CSStransforms).
Furthermore, if you need specific parameters per `CSS Transform property`, you could execute as this [example](http://animejs.com/documentation/#specificPropertyParameters)
Here is your example with these considerations applied. [https://codesandbox.io/s/19q354qn3](https://codesandbox.io/s/19q354qn3).

**Comment by potouridisio** [comment]
Hey @acemir,

You are right. I hadn't thought of it like that (although they seem to be different properties in anime configuration, they refer to one single CSS property).

It is like trying to access CSS property `color` at the same time.

I have to take different approach to my problem.

Thanks!
