### ISSUE TITLE
Library independence.

### ISSUE THREAD

**Issue by trusktr** [juliangarnier/anime#43]
Currently anime.js creates it's own animation loop with `requestAnimationFrame`, which makes it undesirable to add anime.js to an existing project that has it's own loop in which it produces it's own time stamps.

For example, suppose we have a game that makes it's own loop (with `requestAnimationFrame`, or something else in some other JS engine...). In order for anime.js to be integrated into that custom loop, it would be nice for anime.js API to accept a timestamp that was created outside of anime.js.

For a real-world example of an API that is independent in this fashion and can be placed into any existing animation/game loop, see [Tween.js](https://github.com/tweenjs/tween.js/). Note in particular the `.update()` method of the `Tween` class.

---

But! it would also be nice if the anime.js API was able use `requestAnimationFrame` in cases where the developer doesn't already have their own loop. That's something both anime.js and tween.js don't do yet, which would be nice (having both forms of API for both crowds somehow)!

**Comment by SaulDoesCode** [comment]
perhaps a helper function could be exposed to be run with in an external opt-in loop as you suggest. 
Inside the ``requestAnimationFrame`` is abstracted into an engine object. It would not be hard to make the actual content that needs to be looped into a single function and either run it in the default ``engine.play();`` but expose it via maybe ``anime.update()`` using getter that would automagically swap to the external loop. Only problem is that all the animations run in a single ``requestAnimationFrame`` one would have to abstract some more to make the exposed looper function run only the desired animation otherwise it might get complicated. 
This is the internal  ``requestAnimationFrame``  loop.
```javascript
  var engine = (function() {
    var play = function() { raf = requestAnimationFrame(step); };
    var step = function(t) {
      if (animations.length) {
        for (var i = 0; i < animations.length; i++) animations[i].tick(t);
        play();
      } else {
        cancelAnimationFrame(raf);
        raf = 0;
      }
    }
    return play;
  })();
```
I'm going to play around with the concept and see what is possible. I maintain a fork of anime [here](https://github.com/SaulDoesCode/anime-next)

**Comment by ngokevin** [comment]
You can tell anime to not make an RAF.

Set `autoplay: false` and use `.tick(t)` https://github.com/ngokevin/aframe-animation-component/blob/master/index.js#L78

**Comment by ngokevin** [comment]
Actually, looks like that `tick()` I had was a no-op :/

**Comment by juliangarnier** [comment]
Maybe `myAnimation.seek();` can do the trick?
But it's limited, and will not works with loop animations:
````
var myAnimation = anime({
  targets: 'div',
  rotate: 180,
  autoplay: false
});

var raf = 0;
var speed = .5;
var loop = function() {
  myAnimation.seek(raf * speed);
  raf = requestAnimationFrame(loop);
}

requestAnimationFrame(loop);
````

An other option is to use `anime` as your main RAF:
````
var gameLoop = anime({
  update: function() {
    // Do stuff
  },
  duration: Infinity
});
````

**Comment by ngokevin** [comment]
Working on [A-Frame](https://aframe.io), a WebVR framework. Just looking for a way to hook into the existing game loop (without introducing anime into the core library), and a way for anime to not create any `requestAnimationFrame`s. Like tween's global `TWEEN.tick` method.

**Comment by rohan-deshpande** [comment]
Understand that this is closed, but this would be an excellent feature, I'm currently using `animejs` in my `threejs` powered game engine but I am about to consolidate all raf calls into the game loop and, if I understand correctly, this is impossible with `anime`. A real shame because I wouldn't like to drop anime if I didn't have to. Once I do the consolidation I'll have a look under the hood and see what I can do.
