### ISSUE TITLE
Remove animations in docs

### ISSUE THREAD

**Issue by crtl** [juliangarnier/anime#516]
**Is your feature request related to a problem? Please describe.**
The docs look fancy and all but there is no need to use animations in docs (except examples).

**Describe the solution you'd like**
Remove unnecessary UI animations in docs and make the navigation more efficient.

**Additional context**
I am visiting the docs because animejs is a nice library and I need information.
Not because the site is fancy.

**Comment by vaaski** [comment]
please don't remove them, they make navigating the site much more pleasant to look at and perfectly show how anime.js can make a site feel much more fluid and modern.
in my opinion if you were to change something, please focus more on explaining how anime's concepts work instead of just having examples, more like the vue.js documentation.

**Comment by kn0wn** [comment]
Thanks for the comments on the documentation, we will take this into consideration for the next version
