### ISSUE TITLE
How can I support IE 9 & 10?

### ISSUE THREAD

**Issue by jkiss** [juliangarnier/anime#529]
I find that anime support IE 11+, how can I support IE 9 & 10? Does import polyfill work?

**Comment by elliottregan** [comment]
Those browsers are deprecated and unsupported by Microsoft. Continuing to support those probably doesn't make any sense for this project. Try an older version of Anime, or another, older, animation library like Velocity.

My suggestion is, if you _need_ to support dead browsers, to leave a fallback image instead of an animation. Chances are, if a computer is running IE9, it is going to be underpowered by today's standards, and those users will probably appreciate a simple image that doesn't hog the CPU over an animation.

**Comment by jkiss** [comment]
@elliottregan yeah, you are right, thanks!
