### ISSUE TITLE
As one element to make two different animation style one?

### ISSUE THREAD

**Issue by MaximRazon** [juliangarnier/anime#58]
Hi! Faced with the problem of implementation of the toggle:

http://codepen.io/maxrazon/pen/rLRVOJ

**Comment by juliangarnier** [comment]
In this case the animations will be different on each click, depending of the current state of the navbar.
You should call anime directly instead of storing the animations in variables.
Also use `anime.remove()` before animating an already animated element to prevent overlap in animations.

I fixed your example here: http://codepen.io/juliangarnier/pen/xOZQbN

**Comment by MaximRazon** [comment]
Thank you very much!
