### ISSUE TITLE
SVG path animation example

### ISSUE THREAD

**Issue by crnacura** [juliangarnier/anime#66]
First of all, great library, thanks for the awesome work! :) 

I'm having a problem with animating SVG paths in one of our demos:
http://tympanus.net/Development/ItemRevealer/

Do you have any code example with SVG path animations? I'm trying to find out what's wrong with the demo code but it looks like Chrome (53.0.2785.89 (64-bit) on Mac) simply does not animate the SVG paths.

**Comment by juliangarnier** [comment]
Hey thanks for reporting this issue, it's an actual bug.
Looks like Chrome is now returning SVG attributes with `getComputedStyle()`, which I use to determine the animation type (SVG or CSS).
So anime.js will think that you are trying to animate `styles['d']` instead of the `d` attribute.
I have to find a better way to determine the animation type.

Thanks for reporting this! 
I'm on it.

**Comment by juliangarnier** [comment]
Ok I think I found an easy fix can you try with this version?
https://github.com/juliangarnier/anime/blob/svg-path-fix/anime.js

Thanks!

**Comment by crnacura** [comment]
Thanks so much, it works perfectly now! :)
