### ISSUE TITLE
anime transform overriding the elements existing transform

### ISSUE THREAD

**Issue by maaizelahi** [juliangarnier/anime#77]
#button  {
    z-index: 387;
    width: 133px;
    border-width: 0px;
    -webkit-transform: matrix(0,-1,1,0,-2,135);
    -ms-transform: matrix(0,-1,1,0,-2,135);
    transform: matrix(0,-1,1,0,-2,135);
    margin-bottom: -2px;
    position: relative;
    margin-right: -10000px;
    margin-top: -2px;
    left: 307px;
    background: transparent url(../images/thumb3.jpg?crc=39550032) no-repeat center center;
    background-size: cover;
}
"button" already have a transform-matrix. Now if I apply translateX animation 
var anim = anime({
		    targets: button,
		    translateX: 200,
		    duration: config.transition_time,
		    delay: function(el, i) {
		    	return i * 1;
		    },
		    easing: config.ease + 'Sine',
		    update : onUpdate,
		    complete : onComplete
		});

Now button's transform matrix is overridden, however I want bot the transforms to merge/exist together

**Comment by alexchantastic** [comment]
I don't think anime supports preserving existing `transform` properties. As a workaround, you could set the property to animate to the same value in its from and to values like this: http://codepen.io/alexchantastic/pen/GjOzkY

You could then programmatically grab the values that you want to keep the same and just insert them into the array.

@juliangarnier I think this would be a useful feature though so you could set up your initial animation stage with CSS.

**Comment by juliangarnier** [comment]
@maaizelahi : @alexchantastic is right, and setting the initial transform values in your animation is the proper way to achieve what you want to do.

@alexchantastic Agreed, unfortunately getting the initials transforms values with getComputedStyle is tricky
It will return a transform matrix, and the code needed to decode and extract the values from the matrix will double the size of the library!

**Comment by HauntedSmores** [comment]
@juliangarnier Im having a similar issue that was solved by setting the initial transform value. Basically I had an element with `transform: translateX(100%);` and wanted to animate it to `translateX: '0%'` but it was jumping and not really animating. Looked like when the animation kicked in the inline styles it applied for transform overwrote the css rule so the element jumped position (because it no longer had `transform: translateX(100%);` and there fore wasnt then able to be animated to `translateX(0%)`.

I guess my question is, whenever you need to go from one transform rule to another, you just have to put the initial from value in the JS, not CSS?

**Comment by alexchantastic** [comment]
@HauntedSmores, yes that is correct. Anime will ignore (overwrite) existing `transform` properties. For example if you wanted to go from `translateX(100%)` to `translateX(0%)` you would need the following regardless of if `transform: translateX(100%);` was defined in your CSS:

```
anime({
  targets: 'div',
  translateX: [100%, 0%]
});
```

**Comment by juliangarnier** [comment]
@HauntedSmores yes setting the transforms with inline styles is one solution, but it's easier to go with @alexchantastic's answer and use an array.

**Comment by phendan** [comment]
Just stumbled upon this behavior after wondering for a while why my animation was snapping into position instead of animating from a transform I had set in CSS. I suspect I might not be the only one to assume this behavior so a note in the docs that you need to specify the starting keyframe would be of help I think.

Thanks for the great work!
