### ISSUE TITLE
anime.min.js doesn't work

### ISSUE THREAD

**Issue by Naitik-G** [juliangarnier/anime#781]
when i try use this link  <script src="anime.min.js"></script>  in body tag it does not work and when i try this link <script src=
    "https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js">
            </script> in head  it work can you tell me how to fix this

**Comment by Lukas-Batema** [comment]
The most recent version (3.2.1), does not work for me either, the Cloudflare version (3.2.0), which you say is working, is not the most recent version. That may be why. That actually gives me something to try, since I have had trouble getting the most recent version, through `npm I --save animejs`, to work. I was hoping to use the most up-to-date features, but I guess that is not possible. Thanks!

**Comment by juliangarnier** [comment]
Can you describe a bit more what is not working exactly ?
`<script src="anime.min.js"></script>` Should works just fine as long as the file `anime.min.js` is at the same level as your html file.

**Comment by Fefe973** [comment]
Is there a problem with the browser ? Because i get this message error in the console when i launch my script : 
"Uncaught SyntaxError: import declarations may only appear at top level of a module"
i'm on firefox and i saw a question asked in StackOverflow with the same issue, the best answer was that in firefox environnement you should precise in <script tag , a type. like so : <script type="module" src="appthatimports.js"></script> 
but first of all you have to "set to true the variable dom.moduleScripts.enabled  in about:config", i will try this because my script animation isn't working too. And i will try the cloudflare version too like you said.  

StackOverflow : https://stackoverflow.com/questions/42237388/syntaxerror-import-declarations-may-only-appear-at-top-level-of-a-module

**Comment by Xu-Xihe** [comment]
I also faced this questions. I have tried both `npm` and `master.zip` and I think I correctly import it, but it doesn't work. Later, I changed it to `<script src= "https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"></script>` and it worked well!
